### ISSUE TITLE
Playwright test can't be passed in Saucelabs

### ISSUE THREAD

**Issue by emnabn** [saucelabs/saucectl-playwright-example#24]
I have this issue when I try to run : saucectl run
```
Running 0 test using 0 worker


Error: tests\example.test.ts:8:1: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.

   at ..\node_modules\@playwright\test\lib\util.js:221

  219 |
  220 | function errorWithLocation(location, message) {
> 221 |   return new Error(`${formatLocation(location)}: ${message}`);
      |          ^
  222 | }
  223 |
  224 | function expectTypes(receiver, types, matcherName) {

    at errorWithLocation (D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\util.js:221:10)
    at TestTypeImpl._ensureCurrentSuite (D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\testType.js:79:41)
    at TestTypeImpl._createTest (D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\testType.js:88:24)
    at D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\transform.js:269:12
    at Object.<anonymous> (D:\sauce-playwright-runner\2.9.0\bundle\__project__\tests\example.test.ts:8:1)

Error: tests\test.ts:20:20: Playwright Test did not expect test.beforeEach() to be called here.
Most common reasons include:
- You are calling test.beforeEach() in a configuration file.
- You are calling test.beforeEach() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.

   at ..\node_modules\@playwright\test\lib\util.js:221

  219 |
  220 | function errorWithLocation(location, message) {
> 221 |   return new Error(`${formatLocation(location)}: ${message}`);
      |          ^
  222 | }
  223 |
  224 | function expectTypes(receiver, types, matcherName) {

    at errorWithLocation (D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\util.js:221:10)
    at TestTypeImpl._ensureCurrentSuite (D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\testType.js:79:41)
    at TestTypeImpl._hook (D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\testType.js:134:24)
    at Function.beforeEach (D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\transform.js:269:12)
    at Object.<anonymous> (D:\sauce-playwright-runner\2.9.0\bundle\__project__\tests\test.ts:20:20)

=================
 no tests found.
=================

```
In package.json:
```
{
  "name": "par-frontend-ecbiz-test-automation-framework",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "repository": {
    "type": "git",
    "url": "git@gitlab.emobg.io:qa/par/par-frontend-ecbiz-test-automation-framework.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.22.2",
    "allure-playwright": "^2.0.0-beta.18",
    "playwright": "1.22.2",
    "ts-node": "10.8.1",
    "typescript": "4.7.4"

  }
}
```

Can someone help me? thanks

**Comment by alexplischke** [comment]
Could you give us a link to a job where this error occurred?

My guess is that you are not excluding the `node_modules` folder from being uploaded (see `.sauceignore` file). This then causes your uploaded `@playwright/test` lib to interfere with what we have present on the VMs.

**Comment by emnabn** [comment]
thank you for your response.
This is what I put in .sauceignore 
```
.git/
.DS_Store
.hg/
.vscode/
.idea/
.gitignore
.hgignore
.gitlab-ci.yml
.npmrc
*.gif
```
Then I use the same file .sauce as you put in this project.
Just I use typescript tests not javascript ones.

**Comment by alexplischke** [comment]
Yeah, so that confirms my suspicion re:
```
My guess is that you are not excluding the node_modules folder from being uploaded (see .sauceignore file). This then causes your uploaded @playwright/test lib to interfere with what we have present on the VMs.
```

I'd recommend trying https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#dependencies out, if you are keen on uploading `node_modules`. `allure-playwright` and `typescript` are probably the only dependencies that you need to specify. After all, playwright & co. are provided for you already.

**Comment by emnabn** [comment]
Great! thank you I see now, but I have a question when I add the dependencies that i need in yml file :
```
npm:
 dependencies:
   - allure-playwright
   - allure-js-commons
   - tsconfig
   - ts-node
   - typescript
   
  ```
I see that node_modules should be not ignored via .sauceignore. How can I added them in this case ?

**Comment by emnabn** [comment]
I need to include ```playwright-report/ ``` for example, thanks for your help

**Comment by alexplischke** [comment]
Yup, you are on the correct path! To utilize https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#dependencies, follow these steps:

1. Ensure that `node_modules` is _not_ ignored via `.sauceignore`
2. Ensure that all the the dependencies you want are actually present in the `node_modules` folder.
3. Include the deps you want via
```yaml
npm:
 dependencies:
   - allure-playwright
   - allure-js-commons
   - tsconfig
   - ts-node
   - typescript
```

4. And that's it :)
